export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  DISPATCH_NOT_FOUND: "DISPATCH_NOT_FOUND",
  DISPATCH_STATUS_CONFLICT: "DISPATCH_STATUS_CONFLICT",
  RESERVATION_SHORTAGE: "RESERVATION_SHORTAGE",
  RESERVATION_NOT_READY: "RESERVATION_NOT_READY",
  CONCURRENT_APPROVAL: "CONCURRENT_APPROVAL",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
