export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  EVENT_NOT_FOUND: "EVENT_NOT_FOUND",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;
